### ISSUE TITLE
Add Namespace switcher to UI

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/cache-localization-manager#1]

**Comment by Miramas** [comment]
я отправляю по запросу namespace/:namespace
что должно происходить потом?

**Comment by gevorg95** [comment]
@Miramas ничего, просто заново надо подгрузку доминов сделать

**Comment by eduard93** [comment]
Киньте ссылку на код. Как осуществляется "запоминание" namespace?
Не нарушает ли это принцип stateless построения REST API?

**Comment by gevorg95** [comment]
@eduard93 я реализовал не с namespace-ами а с полным путем глобалов, вот так 
`^["namespace"]CacheMsg`

**Comment by eduard93** [comment]
Надо реализовать с URL параметром
