### ISSUE TITLE
clm.utils не компилится.

### ISSUE THREAD

**Issue by Miramas** [intersystems-ru/cache-localization-manager#10]
я пока закоментил этот метод. @gevorg95 посмотришь, из за чего так?
ERROR: CLM.Utils.cls(SetPaths) #1002: Invalid character in tag : 'global=$$$LibsAndDicsPathGlobal' : Offset:106 [zSetPaths^CLM.Utils.1]
 TEXT: zSetPaths(CNAPath,hunspellPath,libcPath,affPath,dicPath,global) public { Set:'($data(global)#2) global=$$$LibsAndDicsPathGlobal

**Comment by gevorg95** [comment]
А, ша сделаю
