### ISSUE TITLE
Export/import feature

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/cache-localization-manager#3]
Let the option of export-import domain resource to xml file.
It's both UI and server-side part
- [x] export
- [x] import

**Comment by Miramas** [comment]
export работает.
с importом какие то проблемы. я отправляю файл на сервер он возврощает следующую ошибку:
`"ERROR #5001: MimeData 'file' is not a file"`

**Comment by gevorg95** [comment]
@Miramas  файл обязательно должен быть XML

**Comment by gevorg95** [comment]
@Miramas Я проверил через постмана и у меня все правильно импортит, попробуй проверить все ли он правильно отправляет.
